openapi: 3.0.0
info:
  title: 'Tools API'
  description: 'A api é um simples repositório para gerenciar ferramentas'
  version: 1.2.0
servers:
  - url: http://ec2-18-117-140-231.us-east-2.compute.amazonaws.com:3000/api
  - url: 'http://localhost:3000/api'
paths:
  /auth/login:
    post:
      tags:
        - auth
      description: 'Rota para realizar o login e obter o token access'
      operationId: 1ff9c65c5cd1a8e0786e318eed856972
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
              type: object
      responses:
        '200':
          description: 'sucesso, retorno do token de acesso'
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
                    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vZWMyLTE4LTExNy0xNDAtMjMxLnVzLWVhc3QtMi5jb21wdXRlLmFtYXpvbmF3cy5jb206MzAwMC9hcGkvYXV0aC9sb2dpbiIsImlhdCI6MTY1MDMwMjQ2OCwiZXhwIjoxNjUwMzA2MDY4LCJuYmYiOjE2NTAzMDI0NjgsImp0aSI6InRkQkFYZ2x0WjQzV1lDazgiLCJzdWIiOiIxIiwicHJ2IjoiODdlMGFmMWVmOWZkMTU4MTJmZGVjOTcxNTNhMTRlMGIwNDc1NDZhYSJ9.v3g2a6yfK8NkIAXv4h_BtVhD0KIuibQyEfv1KKFfl6Y
                  token_type:
                    type: string
                    example: bearer
                  expires_in:
                    type: integer
                    example: 3600
        '401':
          description: 'Erro, crendenciais de acesso inválido'
  /auth/logout:
    post:
      tags:
        - auth
      description: 'Sair do login'
      operationId: eae6a8251a6469bbabe454860f64cf37
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: Successfully logged out
        '401':
          description: 'O token de acesso não foi identificado'
      security:
        -
          bearerAuth: []
  /tools:
    get:
      tags:
        - /tools
      description: 'Lista de ferramentas'
      operationId: 264c3c6aedb3041811e477208fd9c1e6
      parameters:
        -
          name: tag
          in: query
          description: 'filtrar ferramentas utilizando uma busca por tag'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Retorna uma lista de ferramentas'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: Notion,
                    link:
                      type: string
                      example: https://notion.so
                    description:
                      type: string
                      example:  All in one tool to organize teams and ideas. Write, plan, collaborate, and get organized. ,
                    tags:
                      type: array
                      example:
                        - organization,
                        - planning,
                        - collaboration,
                        - writing,
                        - calendar
        '404':
          description: 'Nenhuma ferramenta foi encontrado no banco de dados'
        '401':
          description: 'O token de acesso não foi identificado'
      security:
        -
          bearerAuth: []
    post:
      tags:
        - /tools
      description: 'Criação de nova ferramenta'
      operationId: cda5061c587af842ea863e7cf6092ae2
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                link:
                  type: string
                description:
                  type: string
                tags:
                  type: array
                  items: {  }
              type: object
      responses:
        '201':
          description: 'Opecação bem sucedida. Ferramenta criada com sucesso'
          content:
            application/json:
              schema:
                properties:
                  title:
                    type: string
                  link:
                    type: string
                  description:
                    type: string
                  tags:
                    type: array
                    example:
                        - api
                  id:
                    type: integer
                    example: 6

        '400':
          description: 'Sintaxe JSON inválida'
        '401':
          description: 'O token de acesso não foi identificado'
      security:
        -
          bearerAuth: []
  '/tools/{id}':
    get:
      tags:
        - /tools
      description: 'Exibir detalhes de uma ferramenta'
      operationId: 92cd7623847e952ce2fb0773506e201f
      parameters:
        -
          name: id
          in: path
          description: 'Realizar busca pelo id da ferramenta'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Retorna os detalhes da ferramenta'
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    example: 1
                  title:
                    type: string
                    example: Notion,
                  link:
                    type: string
                    example: https://notion.so
                  description:
                    type: string
                    example:  All in one tool to organize teams and ideas. Write, plan, collaborate, and get organized. ,
                  tags:
                    type: array
                    example:
                      - organization,
                      - planning,
                      - collaboration,
                      - writing,
                      - calendar
        '404':
          description: 'Nenhuma ferramenta foi encontrado no banco de dados'
        '401':
          description: 'O token de acesso não foi identificado'
      security:
        -
          bearerAuth: []
    delete:
      tags:
        - /tools
      description: 'Excluir ferramenta'
      operationId: b877cf3ba4318416dc4bb99ce08a57d8
      parameters:
        -
          name: id
          in: path
          description: 'Realizar a exclusão pelo id da ferramenta'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Operação bem sucedida'
        '401':
          description: 'O token de acesso não foi identificado'
        '404':
          description: 'A ferramenta não foi encotrada para exclusão'
      security:
        -
          bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
